//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Maxima.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMaximaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class MaximaBaseListener : IMaximaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MaximaParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrix([NotNull] MaximaParser.MatrixContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MaximaParser.matrix"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrix([NotNull] MaximaParser.MatrixContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MaximaParser.matrix_rows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrix_rows([NotNull] MaximaParser.Matrix_rowsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MaximaParser.matrix_rows"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrix_rows([NotNull] MaximaParser.Matrix_rowsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MaximaParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterList([NotNull] MaximaParser.ListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MaximaParser.list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitList([NotNull] MaximaParser.ListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IdentifierExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierExp([NotNull] MaximaParser.IdentifierExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IdentifierExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierExp([NotNull] MaximaParser.IdentifierExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>IntegerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerExp([NotNull] MaximaParser.IntegerExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>IntegerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerExp([NotNull] MaximaParser.IntegerExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParenExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenExp([NotNull] MaximaParser.ParenExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParenExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenExp([NotNull] MaximaParser.ParenExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExp([NotNull] MaximaParser.UnaryExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExp([NotNull] MaximaParser.UnaryExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ExpExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpExp([NotNull] MaximaParser.ExpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ExpExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpExp([NotNull] MaximaParser.ExpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MatrixExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMatrixExp([NotNull] MaximaParser.MatrixExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MatrixExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMatrixExp([NotNull] MaximaParser.MatrixExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExp([NotNull] MaximaParser.PowerExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExp([NotNull] MaximaParser.PowerExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>BinaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBinaryExp([NotNull] MaximaParser.BinaryExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BinaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBinaryExp([NotNull] MaximaParser.BinaryExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterListExp([NotNull] MaximaParser.ListExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitListExp([NotNull] MaximaParser.ListExpContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
