//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Maxima.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MaximaParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IMaximaVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MaximaParser.matrix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrix([NotNull] MaximaParser.MatrixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MaximaParser.matrix_rows"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrix_rows([NotNull] MaximaParser.Matrix_rowsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MaximaParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitList([NotNull] MaximaParser.ListContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdentifierExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierExp([NotNull] MaximaParser.IdentifierExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntegerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerExp([NotNull] MaximaParser.IntegerExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExp([NotNull] MaximaParser.ParenExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>UnaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExp([NotNull] MaximaParser.UnaryExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExpExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpExp([NotNull] MaximaParser.ExpExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MatrixExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrixExp([NotNull] MaximaParser.MatrixExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>PowerExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPowerExp([NotNull] MaximaParser.PowerExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BinaryExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinaryExp([NotNull] MaximaParser.BinaryExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ListExp</c>
	/// labeled alternative in <see cref="MaximaParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitListExp([NotNull] MaximaParser.ListExpContext context);
}
